package tech.nocountry.classlodge.course;

public enum CategoryEnum {
    DESARROLLO_WEB,
    PROGRAMACION,
    DISENIO_GRAFICO,
    MARKETING_DIGITAL,
    FINANZAS_PERSONALES,
    IDIOMAS,
    FOTOGRAFIA,
    MUSICA,
    SALUD_Y_BIENESTAR,
    COCINA_Y_GASTRONOMIA,
    ARTE_Y_MANUALIDADES,
    NEGOCIOS_Y_EMPRENDIMIENTO,
    CIENCIAS_DE_DATOS,
    DESARROLLO_PERSONAL,
    EDUCACION_INFANTIL,
    CIENCIAS_NATURALES
}
